POST http://localhost:3000/users/create
content-type: application/json

{
    "username": "sdeaddwe_name",
    "email": "sfleryaa@wtest.com",
    "password": "3456"
}

###
GET http://localhost:3000/users/1 HTTP/1.1
